#!/bin/bash

page=1
if [ "$3" != "" ]
then
  page=$3
fi

if [ "$1" == "" -o "$2" == "" ]
then
  echo "Usage: pdfshadow <input> <output> [page number]"
  exit -1
fi

if [ "`echo $1 | grep pdf`" != "" ]
then
  pdftk $1 cat $page-$page output tmp.pdf
  convert -density 300 tmp.pdf -resize x1000 -flatten tmp0.png 2> /dev/null
  status=$?
  if [ "$status" != "0" ]
  then
    echo "Enforcing color space..."
    convert -density 300 -colorspace RGB tmp.pdf -resize x1000 -flatten tmp0.png > /dev/null
  fi
  format=`file tmp0.png | sed -e "s/,/ /g" | awk '{if ($5>$7) {print "landscape"} else {print "portrait"}}'`
  echo "Format is $format"
  if [ "$format" == "landscape" ]
  then
    resize="1000x"
  else
    resize="x1000"
  fi
  convert tmp0.png -resize $resize -flatten tmp.png
else
  # convert $1 -resize x1000 tmp.png
  cp $1 tmp.png
fi

convert tmp.png -bordercolor white -border 13 \( +clone -background black -shadow 80x4+3+3 \) +swap -background white -layers merge +repage $2

rm -f tmp.pdf tmp0.png tmp.png

exit 0
